name: AWS OIDC Test
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::734228159971:role/roleforpulling
          aws-region: us-east-1

      - name: Test AWS CLI
        run: |
          aws sts get-caller-identity
          aws ecr describe-repositories
